// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn3gPQvmX7bbucxRkW4M6nn1M5TXbOWfk',
    appId: '1:24387968868:web:171255eff1b23b1afb2471',
    messagingSenderId: '24387968868',
    projectId: 'lovetap-48604',
    authDomain: 'lovetap-48604.firebaseapp.com',
    storageBucket: 'lovetap-48604.firebasestorage.app',
    measurementId: 'G-7QSX0XRNXN',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdrA5-hd9JDWbhFVRRtUtzn_KqQhZv-J4',
    appId: '1:24387968868:ios:48b626f71991dc88fb2471',
    messagingSenderId: '24387968868',
    projectId: 'lovetap-48604',
    storageBucket: 'lovetap-48604.firebasestorage.app',
    iosBundleId: 'com.example.flutterLovetap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdrA5-hd9JDWbhFVRRtUtzn_KqQhZv-J4',
    appId: '1:24387968868:ios:48b626f71991dc88fb2471',
    messagingSenderId: '24387968868',
    projectId: 'lovetap-48604',
    storageBucket: 'lovetap-48604.firebasestorage.app',
    iosBundleId: 'com.example.flutterLovetap',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbAeErYSgFY4-sX9KYTdUvexTHkKsGFzM',
    appId: '1:24387968868:android:67b0600424735d04fb2471',
    messagingSenderId: '24387968868',
    projectId: 'lovetap-48604',
    storageBucket: 'lovetap-48604.firebasestorage.app',
  );

}